import type { Audit } from '@/types';

export async function exportToPDF(audit: Audit): Promise<void> {
  // Lazy-load jsPDF in browser only
  const { jsPDF } = await import('jspdf');
  const autoTable = (await import('jspdf-autotable')).default;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Header bar
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('SaaS Auditor Report', margin, 14);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleDateString(), pageWidth - margin, 14, { align: 'right' });

  // Audit name
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(audit.name, margin, 34);

  // Summary cards
  const summaryY = 42;
  const cardData = [
    { label: 'Total Vendors', value: String(audit.vendor_count) },
    { label: 'Monthly Spend', value: `$${audit.total_monthly_cost.toLocaleString('en-US', { minimumFractionDigits: 2 })}` },
    { label: 'Annual Spend', value: `$${audit.total_annual_cost.toLocaleString('en-US', { minimumFractionDigits: 2 })}` },
  ];
  const cardW = (pageWidth - margin * 2 - 8) / 3;
  cardData.forEach((card, i) => {
    const x = margin + i * (cardW + 4);
    doc.setFillColor(239, 246, 255);
    doc.roundedRect(x, summaryY, cardW, 18, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 120);
    doc.text(card.label, x + 4, summaryY + 6);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text(card.value, x + 4, summaryY + 14);
  });

  // Category Breakdown
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Spend by Category', margin, 72);

  autoTable(doc, {
    startY: 76,
    head: [['Category', 'Vendors', 'Monthly', 'Annual', '% of Total']],
    body: audit.category_breakdown.map((c) => [
      c.category,
      String(c.vendor_count),
      `$${c.monthly_cost.toFixed(2)}`,
      `$${c.annual_cost.toFixed(2)}`,
      `${audit.total_monthly_cost > 0 ? ((c.monthly_cost / audit.total_monthly_cost) * 100).toFixed(1) : 0}%`,
    ]),
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8 },
    margin: { left: margin, right: margin },
  });

  const afterCategory = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Subscription table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('All Subscriptions', margin, afterCategory);

  autoTable(doc, {
    startY: afterCategory + 4,
    head: [['Vendor', 'Category', 'Users', 'Billing', 'Monthly', 'Annual']],
    body: audit.subscriptions.map((s) => [
      s.vendor,
      s.category,
      String(s.users_count),
      s.billing_cycle,
      `$${s.monthly_cost.toFixed(2)}`,
      `$${s.annual_cost.toFixed(2)}`,
    ]),
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8 },
    margin: { left: margin, right: margin },
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Generated by SaaS Auditor • Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 6,
      { align: 'center' }
    );
  }

  doc.save(`saas-audit-${audit.name.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`);
}

export function exportToJSON(audit: Audit): void {
  const data = JSON.stringify(audit, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `saas-audit-${audit.name.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}
